const BUILD_PRESETS = {
    "BladeRunner": {
        "description": "High mobility build focused on Reflexes. Utilizes Katanas and Mantis Blades combined with Air Dashes to close gaps instantly.",
        "points": 0,
        "treeData": {
            "Body": {
                "1": 1,
                "2": 1,
                "4": 1,
                "23": 3,
                "24": 1,
                "25": 1,
                "26": 1
            },
            "Reflexes": {
                "2": 1,
                "5": 1,
                "6": 1,
                "8": 2,
                "9": 2,
                "13": 1,
                "15": 1,
                "16": 1,
                "17": 1,
                "18": 1,
                "19": 1,
                "20": 1,
                "21": 3,
                "23": 3,
                "29": 1,
                "30": 1,
                "31": 1,
                "32": 1,
                "33": 1,
                "34": 1,
                "35": 1
            },
            "Technical Ability": {
                "10": 2,
                "11": 1,
                "12": 1,
                "13": 1,
                "14": 1,
                "15": 1,
                "22": 3,
                "23": 1,
                "24": 1,
                "25": 1,
                "33": 1
            },
            "Cool": {
                "2": 1,
                "6": 1,
                "9": 2,
                "10": 1,
                "11": 1,
                "12": 1,
                "13": 1,
                "14": 1,
                "15": 2,
                "16": 1,
                "17": 1,
                "19": 1,
                "20": 3,
                "25": 3,
                "26": 1,
                "27": 1,
                "28": 1,
                "30": 3,
                "31": 1,
                "32": 1,
                "33": 1,
                "34": 1
            }
        }
    },
    "Netrunner God (Overclock)": {
        "description": "Ultimate hacker build. Uses Overclock to sacrifice health for unlimited RAM, spreading quickhacks to entire groups instantly.",
        "points": 0,
        "treeData": {
            "Body": {
                "1": 1,
                "2": 1,
                "4": 1,
                "5": 1,
                "23": 3,
                "24": 1,
                "26": 1,
                "32": 1
            },
            "Reflexes": {
                "1": 1,
                "2": 1,
                "8": 2,
                "13": 1,
                "15": 1,
                "23": 3
            },
            "Technical Ability": {
                "1": 1,
                "3": 1,
                "4": 1,
                "5": 2,
                "9": 1,
                "10": 2,
                "11": 1,
                "12": 1,
                "14": 1,
                "15": 1,
                "16": 3,
                "18": 1,
                "22": 3,
                "24": 1,
                "25": 1,
                "32": 1,
                "33": 1
            },
            "Intelligence": {
                "1": 1,
                "2": 1,
                "6": 1,
                "7": 1,
                "8": 1,
                "9": 2,
                "10": 2,
                "11": 1,
                "12": 1,
                "13": 1,
                "15": 1,
                "18": 1,
                "19": 1,
                "20": 1,
                "21": 1,
                "23": 3,
                "24": 3,
                "25": 2,
                "26": 3,
                "27": 1,
                "29": 1,
                "30": 1,
                "31": 1,
                "32": 1,
                "33": 1,
                "35": 1,
                "36": 1,
                "37": 1,
                "38": 1
            }
        }
    },
    "Solo Tank (Shotgun/LMG)": {
        "description": "Unstoppable force. High Body attribute for massive health regeneration (Adrenaline Rush) and devastation with Shotguns and LMGs.",
        "points": 11,
        "treeData": {
            "Body": {
                "1": 1,
                "2": 1,
                "3": 1,
                "4": 1,
                "5": 1,
                "6": 1,
                "7": 2,
                "8": 1,
                "10": 1,
                "16": 3,
                "17": 1,
                "18": 1,
                "19": 1,
                "20": 1,
                "21": 1,
                "23": 3,
                "24": 1,
                "26": 1,
                "30": 1,
                "31": 1,
                "32": 1
            },
            "Reflexes": {
                "1": 1,
                "2": 1,
                "3": 1,
                "4": 1,
                "8": 2,
                "13": 1,
                "14": 1,
                "15": 1,
                "16": 1,
                "23": 3,
                "32": 1,
                "33": 1
            },
            "Technical Ability": {
                "1": 1,
                "2": 1,
                "3": 1,
                "4": 1,
                "5": 2,
                "9": 1,
                "10": 2,
                "11": 1,
                "12": 1,
                "14": 1,
                "16": 3,
                "17": 1,
                "18": 1,
                "19": 1,
                "21": 1,
                "22": 3,
                "23": 1,
                "24": 1,
                "25": 1,
                "26": 1,
                "32": 1,
                "33": 1
            }
        }
    },
    "Ghost Sniper": {
        "description": "The silent assassin. Focuses on Cool and Reflexes to eliminate enemies with silenced Pistols and Sniper Rifles without ever being detected.",
        "points": 19,
        "treeData": {
            "Body": {
                "1": 1,
                "3": 1,
                "5": 1
            },
            "Reflexes": {
                "2": 1,
                "3": 1,
                "4": 1,
                "6": 1,
                "8": 2,
                "23": 3,
                "34": 1
            },
            "Technical Ability": {
                "10": 2,
                "11": 1,
                "12": 1,
                "13": 1,
                "14": 1,
                "22": 3,
                "23": 1,
                "24": 1,
                "25": 1,
                "26": 1,
                "27": 3,
                "28": 1,
                "29": 1,
                "30": 1,
                "31": 1,
                "33": 1,
                "34": 1
            },
            "Cool": {
                "2": 1,
                "4": 1,
                "5": 1,
                "6": 1,
                "7": 1,
                "9": 2,
                "10": 1,
                "11": 1,
                "12": 1,
                "13": 1,
                "20": 3,
                "21": 1,
                "22": 1,
                "23": 1,
                "24": 1,
                "25": 3,
                "26": 1,
                "27": 1,
                "28": 1,
                "36": 1,
                "37": 1
            }
        }
    },
    "EdgeRunner David Martinez": {
        "description": "David Martinez inspired build. Maxes out Cyberware Capacity and utilizes the Sandevistan for time-dilation combat.",
        "points": 5,
        "treeData": {
            "Body": {
                "1": 1,
                "2": 1,
                "3": 1,
                "4": 1,
                "5": 1,
                "23": 3,
                "24": 1,
                "25": 1,
                "26": 1
            },
            "Reflexes": {
                "1": 1,
                "2": 1,
                "3": 1,
                "4": 1,
                "6": 1,
                "7": 2,
                "8": 2,
                "13": 1,
                "15": 1,
                "22": 3,
                "23": 3,
                "26": 1,
                "27": 1,
                "28": 1,
                "33": 1,
                "34": 1,
                "36": 1
            },
            "Technical Ability": {
                "1": 1,
                "5": 2,
                "7": 1,
                "10": 2,
                "11": 1,
                "12": 1,
                "13": 1,
                "14": 1,
                "15": 1,
                "16": 3,
                "19": 1,
                "21": 1,
                "22": 3,
                "23": 1,
                "24": 1,
                "25": 1,
                "32": 1,
                "33": 1
            },
            "Cool": {
                "1": 1,
                "2": 1,
                "6": 1,
                "9": 2,
                "12": 1,
                "13": 1,
                "20": 3,
                "25": 3,
                "27": 1,
                "28": 1,
                "36": 1,
                "37": 1
            }
        }
    },
    "Semi-stealth Assassin": {
        "description": "A lethal operative who blends subtle infiltration with sudden, decisive attacks, striking from the shadows without fully disappearing into them.",
        "points": 9,
        "treeData": {
            "Body": {
                "1": 1,
                "2": 1,
                "3": 1,
                "4": 1,
                "23": 3,
                "24": 1,
                "25": 1,
                "26": 1,
                "32": 1
            },
            "Technical Ability": {
                "1": 1,
                "3": 1,
                "4": 1,
                "5": 2,
                "9": 1,
                "10": 2,
                "14": 1,
                "22": 3,
                "23": 1,
                "24": 1,
                "25": 1,
                "27": 3,
                "28": 1,
                "29": 1,
                "30": 1,
                "31": 1,
                "33": 1,
                "34": 1
            },
            "Cool": {
                "2": 1,
                "4": 1,
                "5": 1,
                "6": 1,
                "8": 1,
                "9": 2,
                "10": 1,
                "11": 1,
                "12": 1,
                "13": 1,
                "14": 1,
                "15": 2,
                "16": 1,
                "18": 1,
                "19": 1,
                "20": 3,
                "21": 1,
                "22": 1,
                "23": 1,
                "24": 1,
                "25": 3,
                "26": 1,
                "27": 1,
                "28": 1,
                "30": 3,
                "33": 1,
                "35": 1,
                "36": 1
            }
        }
    },

};